# -*- coding: utf-8 -*-
"""thermal_logic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17oGHj8McIVkGdEpVgKgsNOOjRCPJA33K
"""

# pip install pytesseract

# thermal_logic.py

import cv2
import numpy as np
import matplotlib.pyplot as plt

import re
from PIL import Image

try:
    import pytesseract
except ImportError:
    raise ImportError(
        "pytesseract is not installed. "
        "Please install it using: pip install pytesseract"
    )

pytesseract.pytesseract.tesseract_cmd = (
    r"C:\Program Files\Tesseract-OCR\tesseract.exe"
)
# =========================================================
# OCR FUNCTIONS
# =========================================================

def crop_to_temp(crop_bgr):

    # Upscale image for better OCR
    big = cv2.resize(
        crop_bgr,
        (crop_bgr.shape[1] * 8, crop_bgr.shape[0] * 8),
        interpolation=cv2.INTER_LANCZOS4
    )

    # Convert to grayscale
    gray = cv2.cvtColor(big, cv2.COLOR_BGR2GRAY)

    # Threshold
    _, th = cv2.threshold(
        gray,
        150,
        255,
        cv2.THRESH_BINARY
    )

    best = None

    for psm in [7, 8, 13]:

        cfg = f"--psm {psm} -c tessedit_char_whitelist=0123456789."

        txt = pytesseract.image_to_string(
            Image.fromarray(th),
            config=cfg
        ).strip()

        nums = re.findall(r"\d+\.?\d*", txt)

        if nums and best is None:
            best = float(nums[0])

    return best


def has_minus_sign(crop_bgr):

    gray = cv2.cvtColor(crop_bgr, cv2.COLOR_BGR2GRAY)

    bright_rows = [
        r for r in range(gray.shape[0])
        if gray[r].mean() > 100
    ]

    if not bright_rows:
        return False

    box_start = bright_rows[0]
    box_end = bright_rows[-1]

    above = gray[:box_start, :]
    below = gray[box_end + 1:, :]

    def minus_in_region(region):

        if region.shape[0] == 0:
            return False

        for row in range(region.shape[0]):

            row_max = region[row].max()
            row_mean = region[row].mean()

            if row_mean < 80 and row_max > 50:
                return True

        return False

    return (
        minus_in_region(above)
        or
        minus_in_region(below)
    )


# =========================================================
# LUT BUILDING
# =========================================================

def build_lut(scale, t_max, t_min, n_samples=256):

    sh, sw = scale.shape[:2]

    # Crop actual color bar only
    bar_start = int(sh * 0.25)
    bar_end = int(sh * 0.75)

    bar_strip = scale[bar_start:bar_end, :, :]

    rows = np.linspace(
        0,
        bar_strip.shape[0] - 1,
        n_samples,
        dtype=int
    )

    # Average colors across width
    colors = np.array(
        [bar_strip[r].mean(axis=0) for r in rows],
        dtype=np.float32
    )

    # Temperature mapping
    temps = np.linspace(
        t_max,
        t_min,
        n_samples,
        dtype=np.float32
    )

    return colors, temps


def map_pixels_to_temperature(
    image_bgr,
    scale,
    t_max,
    t_min
):

    lut_colors, lut_temps = build_lut(
        scale,
        t_max,
        t_min
    )

    h, w = image_bgr.shape[:2]

    pixels = image_bgr.reshape(-1, 3).astype(np.float32)

    temp_flat = np.zeros(
        pixels.shape[0],
        dtype=np.float32
    )

    batch_size = 10000

    for i in range(0, pixels.shape[0], batch_size):

        batch = pixels[i:i + batch_size]

        diff = (
            batch[:, None, :]
            -
            lut_colors[None, :, :]
        )

        dist = np.sum(diff ** 2, axis=2)

        nearest = np.argmin(dist, axis=1)

        temp_flat[i:i + batch_size] = lut_temps[nearest]

    temp_map = temp_flat.reshape(h, w)

    return temp_map


# =========================================================
# WIRE SEGMENTATION
# =========================================================

def segment_wire_and_compute_delta_t(
    temp_map,
    t_max_scale,
    t_min_scale,
    color_img
):

    h, w = temp_map.shape

    mid_thresh = (
        t_max_scale + t_min_scale
    ) / 2

    roi_mask = np.zeros((h, w), dtype=np.uint8)

    roi_mask[40:h - 40, 160:w - 80] = 1

    above_mid = (
        (temp_map >= mid_thresh)
        &
        (roi_mask == 1)
    ).astype(np.uint8)

    num_labels, labels, stats, _ = cv2.connectedComponentsWithStats(
        above_mid,
        connectivity=8
    )

    wire_mask = np.zeros((h, w), dtype=np.uint8)

    for i in range(1, num_labels):

        area = stats[i, cv2.CC_STAT_AREA]
        bw = stats[i, cv2.CC_STAT_WIDTH]
        bh = stats[i, cv2.CC_STAT_HEIGHT]

        if area < 30:
            continue

        aspect = max(bw, bh) / max(min(bw, bh), 1)

        solidity = area / max(bw * bh, 1)

        is_ui = solidity > 0.50

        is_blob = (
            area > 1500
            and
            solidity > 0.45
            and
            aspect < 3.0
        )

        is_wire = (
            (aspect >= 3.0 or solidity < 0.35)
            and
            area > 30
        )

        if is_wire and not is_ui and not is_blob:

            wire_mask[labels == i] = 1

    # Morphological cleanup
    kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE,
        (3, 3)
    )

    wire_mask = cv2.morphologyEx(
        wire_mask,
        cv2.MORPH_OPEN,
        kernel
    )

    wire_mask = cv2.morphologyEx(
        wire_mask,
        cv2.MORPH_CLOSE,
        kernel
    )

    if wire_mask.sum() == 0:

        return {
            "wire_t_max": None,
            "wire_t_min": None,
            "delta_t": None,
            "alert": "No wire detected",
            "wire_mask": wire_mask
        }

    wire_temps = temp_map[wire_mask == 1]

    wire_t_max = float(
        np.percentile(wire_temps, 99)
    )

    wire_t_min = float(
        np.percentile(wire_temps, 5)
    )

    delta_t = wire_t_max - wire_t_min

    # Alert logic
    if delta_t > 20:

        alert = "CRITICAL - Attend within 24 hrs"

    elif delta_t > 10:

        alert = "WARNING - Attend within 10 days"

    elif delta_t > 5:

        alert = "MONITOR - Attend within 1 month"

    else:

        alert = "NORMAL"

    return {
        "wire_t_max": wire_t_max,
        "wire_t_min": wire_t_min,
        "delta_t": delta_t,
        "alert": alert,
        "wire_mask": wire_mask
    }


# =========================================================
# MAIN PIPELINE
# =========================================================

def process_image(image_path):

    # Load image
    color_img = cv2.imread(image_path)

    # Check image
    if color_img is None:

        raise ValueError(
            f"Failed to load image at {image_path}"
        )

    # =====================================================
    # EXTRACT SCALE
    # =====================================================

    h, w = color_img.shape[:2]

    scale = color_img[
        :,
        int(w * 0.94):int(w * 0.98)
    ]

    # =====================================================
    # CROP TOP/BOTTOM SCALE VALUES
    # =====================================================

    sh, sw = scale.shape[:2]

    top = scale[
        int(sh * 0.13):int(sh * 0.23),
        :
    ]

    bottom = scale[
        int(sh * 0.78):int(sh * 0.88),
        :
    ]

    # =====================================================
    # OCR SCALE TEMPERATURES
    # =====================================================

    t_max_abs = crop_to_temp(top)
    t_min_abs = crop_to_temp(bottom)

    top_is_negative = has_minus_sign(top)
    bot_is_negative = has_minus_sign(bottom)

    t_max = (
        -t_max_abs
        if (top_is_negative and t_max_abs)
        else t_max_abs
    )

    t_min = (
        -t_min_abs
        if (bot_is_negative and t_min_abs)
        else t_min_abs
    )

    # =====================================================
    # SANITY CHECK
    # =====================================================

    if t_max is not None and t_min is not None:

        if t_max < t_min:

            if top_is_negative and not bot_is_negative:

                t_max = t_max_abs

            elif bot_is_negative and not top_is_negative:

                t_min = t_min_abs

            else:

                t_max, t_min = (
                    max(t_max_abs, t_min_abs),
                    min(t_max_abs, t_min_abs)
                )

    # =====================================================
    # CREATE TEMPERATURE MAP
    # =====================================================

    temp_map = map_pixels_to_temperature(
        color_img,
        scale,
        t_max,
        t_min
    )

    # =====================================================
    # SEGMENT WIRE + COMPUTE DELTA T
    # =====================================================

    result = segment_wire_and_compute_delta_t(
        temp_map,
        t_max,
        t_min,
        color_img
    )

    # =====================================================
    # RETURN RESULTS
    # =====================================================

    return {
        "scale_t_max": t_max,
        "scale_t_min": t_min,
        "max_temp": result["wire_t_max"],
        "min_temp": result["wire_t_min"],
        "delta": result["delta_t"],
        "status": result["alert"],
        "temp_map": temp_map,
        "wire_mask": result["wire_mask"]
    }

